### ISSUE TITLE
Add Dockerfile to build easily and locally

### ISSUE THREAD

**Issue by Matts966** [RamyElkest/libvirt-node#41]
Hi, I am interested in getting involved in libvirt project, and libvirt-node for GSoC project. I am currently a student of the University of Tokyo Japan.

I would like to build this project locally but manual headers installation is required. So I currentlly check the build using docker in my local environment.

Is it ok to add Dockerfile and make rule to build this poject in the docker container as PR?

**Comment by RamyElkest** [comment]
Hey @Matts966,

Absolutely, that would be great.

If you need any help let me know
